
# This file is automatically generated, you probably don't want to edit this

overviewOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "overviewOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            sortMode = "original",
            typeFilter = "all",
            issuesDismissed = FALSE, ...) {

            super$initialize(
                package="jglance",
                name="overview",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                default=NULL,
                takeFromDataIfMissing=TRUE,
                permitted=list(
                    "numeric",
                    "factor",
                    "id"))
            private$..sortMode <- jmvcore::OptionList$new(
                "sortMode",
                sortMode,
                hidden=TRUE,
                options=list(
                    "original",
                    "name",
                    "type",
                    "missing-desc"),
                default="original")
            private$..typeFilter <- jmvcore::OptionList$new(
                "typeFilter",
                typeFilter,
                hidden=TRUE,
                options=list(
                    "all",
                    "continuous",
                    "categorical"),
                default="all")
            private$..issuesDismissed <- jmvcore::OptionBool$new(
                "issuesDismissed",
                issuesDismissed,
                hidden=TRUE,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..sortMode)
            self$.addOption(private$..typeFilter)
            self$.addOption(private$..issuesDismissed)
        }),
    active = list(
        vars = function() private$..vars$value,
        sortMode = function() private$..sortMode$value,
        typeFilter = function() private$..typeFilter$value,
        issuesDismissed = function() private$..issuesDismissed$value),
    private = list(
        ..vars = NA,
        ..sortMode = NA,
        ..typeFilter = NA,
        ..issuesDismissed = NA)
)

overviewResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "overviewResults",
    inherit = jmvcore::Group,
    active = list(
        overview = function() private$.items[["overview"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Data Overview")
            self$add(jmvcore::Html$new(
                options=options,
                name="overview",
                title=""))}))

overviewBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "overviewBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jglance",
                name = "overview",
                version = c(1,0,0),
                options = options,
                results = overviewResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Data Overview
#'
#' 
#' @param data .
#' @param vars .
#' @param sortMode .
#' @param typeFilter .
#' @param issuesDismissed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$overview} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
overview <- function(
    data,
    vars = NULL,
    sortMode = "original",
    typeFilter = "all",
    issuesDismissed = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("overview requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    vars <- `if`( ! missing(vars), vars, colnames(data))

    options <- overviewOptions$new(
        vars = vars,
        sortMode = sortMode,
        typeFilter = typeFilter,
        issuesDismissed = issuesDismissed)

    analysis <- overviewClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

