
# This file is automatically generated, you probably don't want to edit this

relationsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relationsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            selectedTarget = "",
            viewMode = "list", ...) {

            super$initialize(
                package="jglance",
                name="relations",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                default=NULL,
                takeFromDataIfMissing=TRUE,
                permitted=list(
                    "numeric",
                    "factor"))
            private$..selectedTarget <- jmvcore::OptionString$new(
                "selectedTarget",
                selectedTarget,
                hidden=TRUE,
                default="")
            private$..viewMode <- jmvcore::OptionString$new(
                "viewMode",
                viewMode,
                hidden=TRUE,
                default="list")

            self$.addOption(private$..vars)
            self$.addOption(private$..selectedTarget)
            self$.addOption(private$..viewMode)
        }),
    active = list(
        vars = function() private$..vars$value,
        selectedTarget = function() private$..selectedTarget$value,
        viewMode = function() private$..viewMode$value),
    private = list(
        ..vars = NA,
        ..selectedTarget = NA,
        ..viewMode = NA)
)

relationsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relationsResults",
    inherit = jmvcore::Group,
    active = list(
        relations = function() private$.items[["relations"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Relations Overview")
            self$add(jmvcore::Html$new(
                options=options,
                name="relations",
                title="",
                clearWith=list(
                    "vars")))}))

relationsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "relationsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jglance",
                name = "relations",
                version = c(1,0,0),
                options = options,
                results = relationsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Relations Overview
#'
#' 
#' @param data .
#' @param vars .
#' @param selectedTarget .
#' @param viewMode .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$relations} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
relations <- function(
    data,
    vars = NULL,
    selectedTarget = "",
    viewMode = "list") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("relations requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))

    vars <- `if`( ! missing(vars), vars, colnames(data))

    options <- relationsOptions$new(
        vars = vars,
        selectedTarget = selectedTarget,
        viewMode = viewMode)

    analysis <- relationsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

